### ISSUE TITLE
Simplify the API (Promises vs Futures)

### ISSUE THREAD

**Issue by JamesWiresmith** [WiresmithTech/Futures-For-LabVIEW#2]
I'm very torn on this so I'm putting this out there for comment.

Right now the API splits the future into two APIs. The "promise" is the writer side as it has a promise to fulfil. The "future" is the reader side as it represents a future value.

### Pros of Split

* As described above, it is a more literal model for each side of the exchange.
* The separate APIs mean we can design the API around the use cases and guide the programmer more. They also can't call methods intended for the other side.

### Pros of Single Class

Instead we could have a single "future" class for both sides.

There is one major benefit. We don't have to explain the difference which may reduce initial confusion and let more people adopt it.

I want to hear your feedback. I have a preference for a split but not if it looks like it will limit adoption for this reason.

**Comment by negentropicdev** [comment]
I'd say split. If there are a bunch of methods available to call that won't work for different contexts then problems will ensue. Splitting is also nice if there's something that might have the same name but get data / operate differently in the different contexts. I think collapsing functionality into a single class is a false simplification because now there are potential methods that can be called and wouldn't be a problem until run-time whereas with separate classes you get edit time errors.

I don't think promises are quite beginner level concepts so I'd stick with designs that give the best bang for the buck in context and IDE usefulness.

**Comment by j-medland** [comment]
I am also on team split for the same reasons as @negentropicdev. If you are extending the functionality to include actions like cancel then I think the split makes even more sense.

**Comment by ansible42** [comment]
I agree on the split for the reasons stated above. I am looking at using this in a framework and having the ability to implement each half on it's own is useful as there will be a bit of stuff to make it work nicely over TCP.

**Comment by JamesWiresmith** [comment]
Excellent - I'm going to leave it as it is for now then.

**Comment by drjdpowell** [comment]
A late reply:
I was about to say that my Future implementation in Messenger Library does not have a separate Promise, but l realized that I effectively do.  My Future is a child class of my Address parent class.  Used as an Address, the Future is effectively a Promise, as one can only send a message to it (the write side).  Only on the read side is the full Future API available.  
Also, because the Future is an Address, the write side already works through the TCP communication in Messenger Library (as all Addresses already do).  

If I count right, there are only 5 base methods in the Futures in Messenger Library.  So be wary of making your APIs much more complex than that.
